### ISSUE TITLE
Hash check against a file

### ISSUE THREAD

**Issue by televisi** [DynamicSadFun/PowerAutomate-HashConnector#2]
Hi,

Thanks for such a great script! 
I raised this as an 'issue', but more a discussion. As I could not find 'discussion' on your github tab.

I wonder whether the hash 2.0 script can be used to check a file checksum, rather than a text input?

Scenario: 
- To run a checksum against 15MB .msi file, 
- if there are any changes to the file (checksum change), to alert myself over email

The following is what I have tried:
1. Save the file to OneDrive
2. Use "OneDrive [get file content](https://learn.microsoft.com/en-au/connectors/onedriveforbusiness/#get-file-content)", to retrieve the file content
3. Pass on the output of file content output to your script
![image](https://github.com/DynamicSadFun/PowerAutomate-HashConnector/assets/4546680/5366f480-a602-4e7b-ae6d-58846aab7b68)

Error: 
_The provided workflow action input is not valid._
![image](https://github.com/DynamicSadFun/PowerAutomate-HashConnector/assets/4546680/fb0fd3d1-fa98-454d-bc6f-55dbfb624524)

Thank you

**Comment by DynamicSadFun** [comment]
Thank you for your comment!
Honestly, that's a good point to add. In general, it makes sense to fix Hash.cs, as it now only works with data represented in string form. If you can somehow convert your file to base64 / blob format, that would work. Otherwise, Hash.cs methods will have to be rewritten to work for files too.
